# Generated by Django 5.0.3 on 2024-03-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('event_num', models.IntegerField()),
                ('is_boys_event', models.BooleanField(default=False)),
                ('event_year', models.IntegerField(default=2024)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MICHEAL', 'MICHEAL'), ('GABRIEL', 'GABRIEL'), ('RAPHAEL', 'RAPHAEL')], max_length=255)),
                ('points', models.FloatField(default=0)),
                ('house_color', models.CharField(default='red', max_length=25)),
                ('position', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.house')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('time_or_distance', models.CharField(max_length=255)),
                ('event_year', models.IntegerField(default=2024)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='core.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt1', models.CharField(default='0m', max_length=255)),
                ('attempt2', models.CharField(default='0m', max_length=255)),
                ('attempt3', models.CharField(default='0m', max_length=255)),
                ('laptime_or_distance', models.CharField(default='0m', max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.event')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core.student')),
            ],
            options={
                'unique_together': {('event', 'student')},
            },
        ),
    ]
