# Generated by Django 5.0.3 on 2024-03-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(choices=[('MICHAEL', 'MICHAEL'), ('GABRIEL', 'GABRIEL'), ('RAPHAEL', 'RAPHAEL')], max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.student'),
        ),
    ]
