# Generated by Django 5.1.7 on 2025-03-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
