# Generated by Django 5.0.3 on 2024-03-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='position',
        ),
    ]
