# Generated by Django 5.1.7 on 2025-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_record_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='best_attempt',
            field=models.FloatField(default=0.0),
        ),
    ]
