# Generated by Django 5.0.3 on 2024-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_house_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_color',
            field=models.CharField(default='red', max_length=10),
        ),
    ]
