# Generated by Django 5.0.3 on 2024-03-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_house_house_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='position',
            field=models.IntegerField(default=4),
        ),
    ]
