# Generated by Django 5.0.3 on 2024-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_record_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='event',
        ),
        migrations.AddField(
            model_name='record',
            name='event',
            field=models.ManyToManyField(related_name='record', to='core.event'),
        ),
    ]
