# Generated by Django 5.0.3 on 2024-03-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_house_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_color',
            field=models.CharField(default='red', max_length=25),
        ),
    ]
