# Generated by Django 5.0.3 on 2024-03-08 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventparticipation_attempt1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.house'),
        ),
    ]
