# Generated by Django 5.0.3 on 2024-03-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_student_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
