# Generated by Django 5.0.3 on 2024-03-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agegroup_event_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.agegroup'),
        ),
    ]
