# Generated by Django 5.0.3 on 2024-03-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_event_age_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age_group',
        ),
        migrations.CreateModel(
            name='AgeGroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agegroup')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
