# Generated by Django 5.0.3 on 2024-03-08 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_event_age_group_agegroupevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.agegroupevent'),
        ),
        migrations.AlterField(
            model_name='record',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='core.agegroupevent'),
        ),
    ]
