# Generated by Django 5.0.3 on 2024-03-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_record_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.CharField(default='Name', max_length=255),
            preserve_default=False,
        ),
    ]
